[package]
name = "diceware"
version = "0.2.0"
authors = ["Yuval Langer <yuval.langer@gmail.com>"]
build = "build.rs"
license = "AGPL-3.0"
repository = "https://gitlab.com/yuvallanger/rusty-diceware"
description = "A command line diceware, sans dice."
keywords = ["diceware", "password", "passphrase", "generator"]
readme = "README.md"


[dependencies]
rand = "^0.5"
getopts = "^0.2"
